name: LumineEconomyBridge
version: 0.1.0
main: com.grapelemon.lumineeconomybridge.LumineEconomyBridge
api-version: '1.21'
authors: [grapelemon]
softdepend: [Vault]
commands:
  le:
    description: Send command to Lumine Economy backend
    usage: /le <content> | /le rewrite | /le start | /le stop | /le reload
    permission: lumineeconomy.le
    aliases: [lumineeconomy]
  let:
    description: Territory utilities for Lumine Economy
    usage: /let protect add [id]
    permission: lumineeconomy.let
    aliases: [lep]
  market:
    description: Open the shared market
    usage: /market [add|remove <shop>]
    permission: lumineeconomy.market
  quest:
    description: Show and accept quests
    usage: /quest [questId]
    permission: lumineeconomy.quest
permissions:
  lumineeconomy.le:
    default: true
  lumineeconomy.admin:
    default: op
  lumineeconomy.let:
    default: true
  lumineeconomy.market:
    default: true
  lumineeconomy.market.admin:
    default: op
  lumineeconomy.quest:
    default: true
